# Action Name
name: Main Automated Builds

# When the Action will Run
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:

permissions: {}

# Workflow Jobs
jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      
      - name: Build
        uses: ricado-group/dotnet-library-build-release-action@v2
        with:
          project-name: 'RICADO.Omron'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          private-nuget-url: 'https://nuget.pkg.github.com/ricado-group/index.json'
          private-nuget-token: ${{ secrets.GH_PACKAGES_PAT }}
          public-nuget-user: ${{ vars.NUGET_USER }}
          publish-public: false
          dotnet-version: 10.0.x
  
  publish:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      
      - name: Build and Publish
        uses: ricado-group/dotnet-library-build-release-action@v2
        with:
          project-name: 'RICADO.Omron'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          private-nuget-url: 'https://nuget.pkg.github.com/ricado-group/index.json'
          private-nuget-token: ${{ secrets.GH_PACKAGES_PAT }}
          public-nuget-user: ${{ vars.NUGET_USER }}
          publish-public: true
          dotnet-version: 10.0.x
